### ISSUE TITLE
Recursion Support

### ISSUE THREAD

**Issue by OrenGitHub** [aeflores/CoFloCo#29]
Hi!
We are experimenting with CoFloCo web interface and it works great.
However, it seems that we can not analyze recursive functions.
For example when we tried the following, nothing happened:
```
void scan_rec(int n)
{
    if (n <= 1) return;
    else scan_rec(n-1);
}
```
Other examples we tried worked fine,
are we doing something wrong?
Thanks!

**Comment by aeflores** [comment]
Hi!
The short answer is no. Unfortunately this is expected.
CoFloCo supports recursion (in fact everything is recursion for CoFloCo) but to analyze C programs we use a couple of translation scripts (https://github.com/aeflores/CoFloCo/tree/master/interfaces/C2ces) that do not support recursive procedures at the moment.

SACO (https://costa.fdi.ucm.es/saco/web/) is another web interface that can use CoFloCo as a backend (you have to select it explicitly as it uses PUBS by default) and supports recursive methods. It does not analyze C programs but rather ABS programs (a java-like language) but you might want to try recursive procedures there.

On the other hand, making the required changes in the translation from C to support recursion should be doable. I could try to find the time for it.
