### ISSUE TITLE
Is the Web interface down?

### ISSUE THREAD

**Issue by corwin-of-amber** [aeflores/CoFloCo#31]
We have not been able to access http://cofloco.se.informatik.tu-darmstadt.de for some time.

**Comment by aeflores** [comment]
Yes, it is, and it is not coming back up for the time being. I am not in that institution anymore, and I don't have a place to host it.
I have updated the README accordingly.

If you just want to try CoFloCo, I suggest you use its docker image `afloresmontoya/cofloco` (See README for more details).

**Comment by corwin-of-amber** [comment]
Actually what I am most interested in is the C programs used in the demo and evaluation. The files in `examples/evaluation/c-examples` are in ces format, I assume after having been processed with clang + llvm2kittel. Can you provide just the C sources?

**Comment by aeflores** [comment]
Sure, they are all here http://aeflores.github.io/CoFloCo/experimentsPhD/experiments.tar.bz2 mostly under the `examples_literature` subdirectory.

**Comment by corwin-of-amber** [comment]
This is wonderful! Thank you so much.
